### PR TITLE
pkg/ip: Return correct error if container name provided exists, and test cases

### LINKED ISSUE #155: failed to find a unique veth name
This error message happens to appear when the interface inside the container already exists, and this is supposed to be unreachable code... not sure what's exactly going on here.

What I'm doing is:
```
echo '{
  "bridge":"cbr0",
  "ipMasq":true,
  "ipam":{"routes":[{"dst":"0.0.0.0/0"}],"subnet":"10.240.1.0/24","type":"host-local"},
  "isGateway":true,
  "name":"kubenet",
  "type":"bridge"
}' \
  | env \
    CNI_COMMAND=ADD \
    CNI_CONTAINERID=5709bbff004a100c0a69837654f9d42c93cca6ff070f7a2509f2ebffb68ffe2a \
    CNI_NETNS=/proc/23995/ns/net CNI_IFNAME=eth12 CNI_PATH=/opt/cni/bin:/opt/bridge/bin \
   /opt/cni/bin/bridge
```
And this command works the first time, but returns the "failed to find a unique veth name" on the second run. If I bump `CNI_IFNAME`, it works again.

### PR DESCRIPTION
**Pull request by prateekgogia**
If interface name for a container provided by a user is already present,
Veth creation fails with incorrect error.
If os.IsExist error is returned by makeVethPair:
* Check for peer name, if exists generate another random peer name, 
* else, IsExist error is due to container interface present, return error.

Fixes #155

### CODE REVIEW

**Comment by rosenhouse** [comment]
@prateekgogia: Thank you for the fix.  Could you please update it to follow [our contribution guidelines](https://github.com/containernetworking/cni/blob/master/CONTRIBUTING.md)?  

Specifically:
- Please add test coverage for your change. 
- Please format your commit message(s) according to the preferred style.

For this change, the test case is non-trivial.  I'd suggest testing `ip.SetupVeth` by temporarily replacing `rand.Reader` in the [`BeforeEach` block](http://onsi.github.io/ginkgo/#structuring-your-specs).  You can replace it with a deterministic `io.Reader` (e.g. one that always returns 0s).  In the `It` blocks you can then call `SetupVeth` repeatedly and write expectations on the resulting behavior.  But `rand.Reader` is a process-global variable, so don't forget set it back to the original value (e.g. in the [`AfterEach()` block](http://onsi.github.io/ginkgo/#structuring-your-specs)) so as not to pollute other test cases that use it.

**Comment by prateekgogia** [comment]
Hi @rosenhouse Thanks for the feedback. I am not familiar with Ginkgo testing framework. I will read about it and add the test cases soon.

**Comment by prateekgogia** [comment]
Hi @rosenhouse - I have made the changes to commit message and added test cases, can you please review and let me know if anything else is required.

File: pkg/ip/link.go [hunk 1]
```diff
@@ -41,6 +41,15 @@ func makeVethPair(name, peer string, mtu int) (netlink.Link, error) {
 	return veth, nil
 }
 
+func peerExists(name string) bool {
+
+	link, err := netlink.LinkByName(name)
+	if link == nil || err != nil {
```
Comment (rosenhouse) [inline pkg/ip/link.go]: The test suite still passes if I simplify this to
```go
_, err := netlink.LinkByName(name)
if err != nil {
   ...
```

File: pkg/ip/link_test.go [hunk 2]
```diff
@@ -102,6 +110,63 @@ var _ = Describe("Link", func() {
 		})
 	})
 
+	It("SetupVeth must return an Error if interface already exist in container ns", func() {
```
Comment (rosenhouse) [inline pkg/ip/link_test.go]:
```go
It("returns an error if the container already has an interface with the same name", func() {
```

File: pkg/ip/link_test.go [hunk 3]
```diff
@@ -102,6 +110,63 @@ var _ = Describe("Link", func() {
...
+			defer GinkgoRecover()
+
+			_, _, err := ip.SetupVeth(containerVethName, mtu, hostNetNS)
+			Expect(err.Error()).To(Equal(fmt.Sprintf("container veth name provided (%s) already exists", containerVethName)))
+
+			return nil
+		})
+	})
+
+	It("SetupVeth must return an Error if interface already exist in the host ns", func() {
```
Comment (rosenhouse) [inline pkg/ip/link_test.go]:
```go
Context("when there is no name available for the host-side", func() {
   BeforeEach(func() {
        containerVethName += "0"
   })
   It("returns a useful error", func() {
          ...
```

File: pkg/ip/link_test.go [hunk 4]
```diff
@@ -102,6 +110,63 @@ var _ = Describe("Link", func() {
...
+			//adding different interface to container ns
+			containerVethName = containerVethName + "0"
+			_, _, err := ip.SetupVeth(containerVethName, mtu, hostNetNS)
+			Expect(err.Error()).To(Equal("failed to move veth to host netns: file exists"))
+
+			return nil
+		})
+	})
+
+	It("SetupVeth should not return an Error when another veth pair is added to namespaces", func() {
```
Comment (rosenhouse) [inline pkg/ip/link_test.go]:
```go
Context("when there is no name conflict for the host or container interfaces", func() {
   BeforeEach(func() {
	containerVethName += "0"
	rand.Reader = originalRandReader
   })
   It("successfully creates the second veth pair", func() {
      ...
```

**Comment by rosenhouse** [comment]
Hi @prateekgogia,

Thank you so much, this test coverage is a huge improvement.

I noticed a small code simplification and also left some suggestions for improving the readability of the tests. The Ginkgo / Gomega BDD style is most valuable when the `Describe`, `Context` and `It` blocks all read as clear sentences.

I'd ask that you fix these up, and then squash all of your commits together into a single commit that follows the aforementioned style guidelines.

Thanks!

**Comment by prateekgogia** [comment]
@rosenhouse: updated and squashed all commits in one commit. Thanks for the review :)

File: pkg/ip/link.go [hunk 5]
```diff
@@ -41,6 +41,15 @@ func makeVethPair(name, peer string, mtu int) (netlink.Link, error) {
 	return veth, nil
 }
 
+func peerExists(name string) bool {
+
```
Comment (jellonek) [inline pkg/ip/link.go]: Please remove this empty line.

File: pkg/ip/link.go [hunk 6]
```diff
@@ -41,6 +41,15 @@ func makeVethPair(name, peer string, mtu int) (netlink.Link, error) {
...
+	_, err := netlink.LinkByName(name)
+	if err != nil {
```
Comment (jellonek) [inline pkg/ip/link.go]: If any returned values (_, err) isn't used out of "if" block - this should be combined into:
```
  if _, err := netlink.LinkByName(name); err != nil {
```
Like shown in second example in https://golang.org/doc/effective_go.html#if

**Comment by prateekgogia** [comment]
@rosenhouse @jellonek addressed.

**Comment by rosenhouse** [comment]
LGTM.  Any other @containernetworking/cni-maintainers want to give the second 👍 ?

**Comment by jellonek** [comment]
LGTM, but i'm not maintainer.

**Comment by tomdee** [comment]
LGTM - merging.
