### PR TITLE
pkg/ns: verify netns when initialized with GetNS

### LINKED ISSUE #221: pkg/ns: doesn't ensure that the stored fd is a valid network namespace
My concern is if we initialize a `ns.NetNS` object using `ns.GetNS(path)` and _path_ points to just an empty file without any network namespace mounted on top, we don't detect that. 
We'll eventually throw an error, but that is simply from the attempt to execute `ns.Do()` and `ns.Set()` which will try to switch the network namespace, which will fail.

I suggest that we introduce validation of the file and set the `mounted` flag respectively. Furthermore, if `mounted == false`, we shouldn't attempt to switch the network namespace at all.

### PR DESCRIPTION
**Pull request by steveeJ**
Fixes #221.

### CODE REVIEW

File: pkg/ns/ns.go [hunk 1]
```diff
@@ -74,11 +75,22 @@ func GetCurrentNS() (NetNS, error) {
...
+
+	stat := syscall.Statfs_t{}
+	if err = syscall.Statfs(nspath, &stat); err != nil {
+		return nil, fmt.Errorf("Failed to Statfs %v: %v", nspath, err)
 	}
-	return &netNS{file: fd}, nil
+
+	return &netNS{
+		file:    fd,
+		mounted: stat.Type == NSFS_MAGIC,
```
Comment (dcbw) [inline pkg/ns/ns.go]: I wouldn't set mounted:true for plain GetNS() calls.  The  reason is because only the creator of the netns should be disposing of it via ns.Close(), and things that call GetNS() are the creator.  I think all you want to do here is return an error if the mountpoint is not an NSFS mount point.

File: pkg/ns/ns.go [hunk 2]
```diff
@@ -179,7 +191,28 @@ func (ns *netNS) Close() error {
...
 }
 
+func (ns *netNS) validate(action string) error {
+	switch {
+	case ns.file == nil:
+		return fmt.Errorf(
+			"%q failed: no filedescriptor associated",
+			action,
+		)
+	case ns.mounted == false:
```
Comment (dcbw) [inline pkg/ns/ns.go]: We don't care if some paths aren't mounted; we only care that ones created through NewNS() are mounted.  For example, a CNI plugin that is passed a namespace path needs to close the file handle with Close(), and if mounted:true then pkg/ns will also try to unmount it and remove the mountpoint when Close() is called.  We only want that to happen for things that pkg/ns creates with NewNS(), not for any random namespace passed into the process.

Comment (dcbw) [inline pkg/ns/ns.go]: Possibly we should rename 'mounted' to 'cni_created' or something like that?

File: pkg/ns/ns.go [hunk 3]
```diff
@@ -179,7 +191,28 @@ func (ns *netNS) Close() error {
...
+			"%q failed: no network namespace mounted on file %q",
+			action, ns.file.Name,
+		)
+	}
+
+	return nil
+}
+
 func (ns *netNS) Do(toRun func(NetNS) error) error {
+	if err := ns.validate("Do"); err != nil {
```
Comment (dcbw) [inline pkg/ns/ns.go]: Why bother calling validate() here?  Shouldn't ensuring validity on GetNS() be sufficient?  If we hold an open file handle to the namespace, it can't have been closed yet and it can't have been unmounted, so it should be sufficient to check that it's NSFS_MAGIC on GetNS() and then we're good, I'm pretty sure.

File: pkg/ns/ns.go [hunk 4]
```diff
@@ -218,6 +251,10 @@ func (ns *netNS) Do(toRun func(NetNS) error) error {
 }
 
 func (ns *netNS) Set() error {
+	if err := ns.validate("Set"); err != nil {
```
Comment (dcbw) [inline pkg/ns/ns.go]: Same comment as Do()...

File: pkg/ns/ns.go [hunk 5]
```diff
@@ -74,11 +75,22 @@ func GetCurrentNS() (NetNS, error) {
...
+		return nil, fmt.Errorf("Failed to open %v: %v", nspath, err)
+	}
+
+	stat := syscall.Statfs_t{}
+	if err = syscall.Statfs(nspath, &stat); err != nil {
+		return nil, fmt.Errorf("Failed to Statfs %v: %v", nspath, err)
 	}
-	return &netNS{file: fd}, nil
+	if stat.Type != NSFS_MAGIC {
+		return nil, fmt.Errorf("no network namespace mounted on file %q", nspath)
```
Comment (dcbw) [inline pkg/ns/ns.go]: Have to close the fd here on error.

File: pkg/ns/ns.go [hunk 6]
```diff
@@ -74,11 +75,22 @@ func GetCurrentNS() (NetNS, error) {
...
+	const NSFS_MAGIC = 0x6e736673
+
 	fd, err := os.Open(nspath)
 	if err != nil {
-		return nil, err
+		return nil, fmt.Errorf("Failed to open %v: %v", nspath, err)
+	}
+
+	stat := syscall.Statfs_t{}
+	if err = syscall.Statfs(nspath, &stat); err != nil {
```
Comment (dcbw) [inline pkg/ns/ns.go]: have to close the fd here on error.

File: pkg/ns/ns.go [hunk 7]
```diff
@@ -74,11 +75,22 @@ func GetCurrentNS() (NetNS, error) {
...
+		return nil, fmt.Errorf("Failed to Statfs %v: %v", nspath, err)
 	}
-	return &netNS{file: fd}, nil
+	if stat.Type != NSFS_MAGIC {
+		return nil, fmt.Errorf("no network namespace mounted on file %q", nspath)
+	}
+
+	return &netNS{file: fd, mounted: true}, nil
```
Comment (dcbw) [inline pkg/ns/ns.go]: The Travis tests are failing because of this mounted:true.  Per my other comments, I don't think we should set mounted:true for namespaces that pkg/ns doesn't itself create, since that will attempt to unmount the namespace which is going to fail if other holders have it open.  Only the creator of the namespace should try to unmount it on Close().

**Comment by dcbw** [comment]
My take on this would be https://github.com/dcbw/cni/commits/namespace-validate ...

File: pkg/ns/ns.go [hunk 8]
```diff
@@ -76,11 +77,31 @@ func GetCurrentNS() (NetNS, error) {
 func GetNS(nspath string) (NetNS, error) {
 	fd, err := os.Open(nspath)
 	if err != nil {
+		return nil, fmt.Errorf("Failed to open %v: %v", nspath, err)
+	}
+
+	isNSFS, err := IsNSFS(nspath)
+	if err != nil {
```
Comment (dcbw) [inline pkg/ns/ns.go]: Still need to close the FD here on error return.

File: pkg/ns/ns.go [hunk 9]
```diff
@@ -76,11 +77,31 @@ func GetCurrentNS() (NetNS, error) {
...
 		return nil, err
 	}
+	if !isNSFS {
```
Comment (dcbw) [inline pkg/ns/ns.go]: Still need to close the FD here on error return.

File: pkg/ns/ns.go (hunk 8 above)
Comment (steveeJ) [inline pkg/ns/ns.go]: Thanks!

**Comment by dcbw** [comment]
LGTM now, but how about some tests like:

```golang
		It("fails when the path is not a namespace", func() {
			tempFile, err := ioutil.TempFile("", "nstest")
			Expect(err).NotTo(HaveOccurred())
			defer tempFile.Close()
			defer os.Remove(tempFile.Name())

			_, err = ns.GetNS(tempFile.Name())
			Expect(err).To(MatchError(fmt.Sprintf("no network namespace mounted on file %q", tempFile.Name())))
		})
```

**Comment by steveeJ** [comment]
> LGTM now, but how about some tests like:

Right, always good to have more tests! I fleshed your draft out and added a test case.

**Comment by dcbw** [comment]
> Right, always good to have more tests! I fleshed your draft out and added a test case.

Thanks, test LGTM.
